// Each new term in the Fibonacci sequence is generated by adding the previous two terms. By starting with  and , the first terms will be:

// By considering the terms in the Fibonacci sequence whose values do not exceed four million, find the sum of the even-valued terms.

import { isMultipleOf } from "../common/common"

export function fib(x: number): number {
    if (x < 0) {
        throw new RangeError("Number needs to be positive")
    }
    if (x === 0) {
        return 0
    } else if (x ===1) {
        return 1
    } else {
        return fib(x-1) + fib(x-2)
    }
}

let x = 0
let res = 0
while ( fib(x) < 4000000 ) {
    if ( isMultipleOf(fib(x),2) ) {
        res = res + fib(x)
    }
    x += 1
}

console.log("The sum of all the even fibonacci numbers which value is under 4000000 is:", res)